spring:
  profiles:
    active: test
  application:
    name: wtm
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa;NON_KEYWORDS=USER;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # show_sql: true
        format_sql: true
      use_sql_comments: true
  # paging ?? size global default ??
#  data:
#    web:
#      pageable:
#        default-page-size: 10

logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type: trace

app:
  jwtSecret:
  jwtExpirationMs:


